// Code generated by 'yaegi extract github.com/godevsig/grepo/util/fileserver'. DO NOT EDIT.

// +build fileserver

package extension

import (
	"github.com/godevsig/grepo/util/fileserver"
	"reflect"
)

func init() {
	Symbols["github.com/godevsig/grepo/util/fileserver/fileserver"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewFileServer": reflect.ValueOf(fileserver.NewFileServer),

		// type definitions
		"FileServer": reflect.ValueOf((*fileserver.FileServer)(nil)),
	}
}
