// Code generated by 'yaegi extract github.com/godevsig/grepo/lib/sys/shell'. DO NOT EDIT.

// +build shell

package extension

import (
	"github.com/godevsig/grepo/lib/sys/shell"
	"reflect"
)

func init() {
	Symbols["github.com/godevsig/grepo/lib/sys/shell/shell"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Run": reflect.ValueOf(shell.Run),
	}
}
