// Code generated by 'yaegi extract github.com/godevsig/grepo/recorder'. DO NOT EDIT.

//go:build recorder
// +build recorder

package extension

import (
	"github.com/godevsig/grepo/recorder"
	"reflect"
)

func init() {
	Symbols["github.com/godevsig/grepo/recorder/recorder"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewServer": reflect.ValueOf(recorder.NewServer),

		// type definitions
		"Server":          reflect.ValueOf((*recorder.Server)(nil)),
		"SessionRequest":  reflect.ValueOf((*recorder.SessionRequest)(nil)),
		"SessionResponse": reflect.ValueOf((*recorder.SessionResponse)(nil)),
	}
}
func init() {
	Symbols["github.com/godevsig/grepo/recorder/recorder/recorder"] = map[string]reflect.Value{
		// type definitions
		"SessionRequest":  reflect.ValueOf((*recorder.SessionRequest)(nil)),
		"SessionResponse": reflect.ValueOf((*recorder.SessionResponse)(nil)),
	}
}
