// Code generated by 'yaegi extract github.com/godevsig/grepo/lib/sys/log'. DO NOT EDIT.

//go:build log
// +build log

package extension

import (
	"github.com/godevsig/grepo/lib/sys/log"
	"reflect"
)

func init() {
	Symbols["github.com/godevsig/grepo/lib/sys/log/log"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultStream":       reflect.ValueOf(&log.DefaultStream).Elem(),
		"GetStream":           reflect.ValueOf(log.GetStream),
		"LUTC":                reflect.ValueOf(log.LUTC),
		"Ldebug":              reflect.ValueOf(log.Ldebug),
		"Ldefault":            reflect.ValueOf(log.Ldefault),
		"Lerror":              reflect.ValueOf(log.Lerror),
		"Lfatal":              reflect.ValueOf(log.Lfatal),
		"Lfileline":           reflect.ValueOf(log.Lfileline),
		"Linfo":               reflect.ValueOf(log.Linfo),
		"Linvalid":            reflect.ValueOf(log.Linvalid),
		"Ltrace":              reflect.ValueOf(log.Ltrace),
		"Lwarn":               reflect.ValueOf(log.Lwarn),
		"NewStream":           reflect.ValueOf(log.NewStream),
		"RegOutputterFactory": reflect.ValueOf(log.RegOutputterFactory),
		"StringToLoglevel":    reflect.ValueOf(log.StringToLoglevel),

		// type definitions
		"Flag":             reflect.ValueOf((*log.Flag)(nil)),
		"Logger":           reflect.ValueOf((*log.Logger)(nil)),
		"Loglevel":         reflect.ValueOf((*log.Loglevel)(nil)),
		"Outputter":        reflect.ValueOf((*log.Outputter)(nil)),
		"OutputterFactory": reflect.ValueOf((*log.OutputterFactory)(nil)),
		"Stream":           reflect.ValueOf((*log.Stream)(nil)),

		// interface wrapper definitions
		"_Outputter":        reflect.ValueOf((*_github_com_godevsig_grepo_lib_sys_log_Outputter)(nil)),
		"_OutputterFactory": reflect.ValueOf((*_github_com_godevsig_grepo_lib_sys_log_OutputterFactory)(nil)),
	}
}

// _github_com_godevsig_grepo_lib_sys_log_Outputter is an interface wrapper for Outputter type
type _github_com_godevsig_grepo_lib_sys_log_Outputter struct {
	IValue interface{}
	WWrite func(p []byte) (n int, err error)
}

func (W _github_com_godevsig_grepo_lib_sys_log_Outputter) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_godevsig_grepo_lib_sys_log_OutputterFactory is an interface wrapper for OutputterFactory type
type _github_com_godevsig_grepo_lib_sys_log_OutputterFactory struct {
	IValue        interface{}
	WNewOutputter func(description string) (log.Outputter, error)
}

func (W _github_com_godevsig_grepo_lib_sys_log_OutputterFactory) NewOutputter(description string) (log.Outputter, error) {
	return W.WNewOutputter(description)
}
