// Code generated by 'yaegi extract github.com/godevsig/grepo/perf/topidchart'. DO NOT EDIT.

// +build topidchart

package extension

import (
	"github.com/godevsig/grepo/perf/topidchart"
	"reflect"
)

func init() {
	Symbols["github.com/godevsig/grepo/perf/topidchart/topidchart"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewServer": reflect.ValueOf(topidchart.NewServer),
		"ParseFile": reflect.ValueOf(topidchart.ParseFile),

		// type definitions
		"ProcessInfo":     reflect.ValueOf((*topidchart.ProcessInfo)(nil)),
		"Record":          reflect.ValueOf((*topidchart.Record)(nil)),
		"Server":          reflect.ValueOf((*topidchart.Server)(nil)),
		"SessionRequest":  reflect.ValueOf((*topidchart.SessionRequest)(nil)),
		"SessionResponse": reflect.ValueOf((*topidchart.SessionResponse)(nil)),
		"SysInfo":         reflect.ValueOf((*topidchart.SysInfo)(nil)),
	}
}
func init() {
	Symbols["github.com/godevsig/grepo/perf/topidchart/topidchart/topidchart"] = map[string]reflect.Value{
		// type definitions
		"ProcessInfo":     reflect.ValueOf((*topidchart.ProcessInfo)(nil)),
		"Record":          reflect.ValueOf((*topidchart.Record)(nil)),
		"SessionRequest":  reflect.ValueOf((*topidchart.SessionRequest)(nil)),
		"SessionResponse": reflect.ValueOf((*topidchart.SessionResponse)(nil)),
		"SysInfo":         reflect.ValueOf((*topidchart.SysInfo)(nil)),
	}
}
