// Code generated by 'yaegi extract github.com/godevsig/adaptiveservice'. DO NOT EDIT.

// +build adaptiveservice

package extension

import (
	"github.com/godevsig/adaptiveservice"
	"go/constant"
	"go/token"
	"net"
	"reflect"
)

func init() {
	Symbols["github.com/godevsig/adaptiveservice/adaptiveservice"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BuiltinPublisher":       reflect.ValueOf(constant.MakeFromLiteral("\"builtin\"", token.STRING, 0)),
		"ErrConnReset":           reflect.ValueOf(&adaptiveservice.ErrConnReset).Elem(),
		"ErrServerClosed":        reflect.ValueOf(&adaptiveservice.ErrServerClosed).Elem(),
		"ErrServiceNotFound":     reflect.ValueOf(adaptiveservice.ErrServiceNotFound),
		"ErrServiceNotReachable": reflect.ValueOf(&adaptiveservice.ErrServiceNotReachable).Elem(),
		"NewClient":              reflect.ValueOf(adaptiveservice.NewClient),
		"NewServer":              reflect.ValueOf(adaptiveservice.NewServer),
		"NewStreamIO":            reflect.ValueOf(adaptiveservice.NewStreamIO),
		"OK":                     reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"OnConnectFunc":          reflect.ValueOf(adaptiveservice.OnConnectFunc),
		"OnDisconnectFunc":       reflect.ValueOf(adaptiveservice.OnDisconnectFunc),
		"OnNewStreamFunc":        reflect.ValueOf(adaptiveservice.OnNewStreamFunc),
		"RegisterType":           reflect.ValueOf(adaptiveservice.RegisterType),
		"ScopeAll":               reflect.ValueOf(adaptiveservice.ScopeAll),
		"ScopeLAN":               reflect.ValueOf(adaptiveservice.ScopeLAN),
		"ScopeOS":                reflect.ValueOf(adaptiveservice.ScopeOS),
		"ScopeProcess":           reflect.ValueOf(adaptiveservice.ScopeProcess),
		"ScopeWAN":               reflect.ValueOf(adaptiveservice.ScopeWAN),
		"SrvLANRegistry":         reflect.ValueOf(constant.MakeFromLiteral("\"LANRegistry\"", token.STRING, 0)),
		"SrvProviderInfo":        reflect.ValueOf(constant.MakeFromLiteral("\"providerInfo\"", token.STRING, 0)),
		"SrvRegistryInfo":        reflect.ValueOf(constant.MakeFromLiteral("\"registryInfo\"", token.STRING, 0)),
		"SrvReverseProxy":        reflect.ValueOf(constant.MakeFromLiteral("\"reverseProxy\"", token.STRING, 0)),
		"SrvServiceLister":       reflect.ValueOf(constant.MakeFromLiteral("\"serviceLister\"", token.STRING, 0)),
		"WithLogger":             reflect.ValueOf(adaptiveservice.WithLogger),
		"WithProviderID":         reflect.ValueOf(adaptiveservice.WithProviderID),
		"WithQsize":              reflect.ValueOf(adaptiveservice.WithQsize),
		"WithRegistryAddr":       reflect.ValueOf(adaptiveservice.WithRegistryAddr),
		"WithScope":              reflect.ValueOf(adaptiveservice.WithScope),

		// type definitions
		"Client":              reflect.ValueOf((*adaptiveservice.Client)(nil)),
		"Connection":          reflect.ValueOf((*adaptiveservice.Connection)(nil)),
		"Context":             reflect.ValueOf((*adaptiveservice.Context)(nil)),
		"ContextStream":       reflect.ValueOf((*adaptiveservice.ContextStream)(nil)),
		"HighPriorityMessage": reflect.ValueOf((*adaptiveservice.HighPriorityMessage)(nil)),
		"KnownMessage":        reflect.ValueOf((*adaptiveservice.KnownMessage)(nil)),
		"ListService":         reflect.ValueOf((*adaptiveservice.ListService)(nil)),
		"Logger":              reflect.ValueOf((*adaptiveservice.Logger)(nil)),
		"LoggerAll":           reflect.ValueOf((*adaptiveservice.LoggerAll)(nil)),
		"LoggerNull":          reflect.ValueOf((*adaptiveservice.LoggerNull)(nil)),
		"LowPriorityMessage":  reflect.ValueOf((*adaptiveservice.LowPriorityMessage)(nil)),
		"Netconn":             reflect.ValueOf((*adaptiveservice.Netconn)(nil)),
		"Option":              reflect.ValueOf((*adaptiveservice.Option)(nil)),
		"ReqProviderInfo":     reflect.ValueOf((*adaptiveservice.ReqProviderInfo)(nil)),
		"Scope":               reflect.ValueOf((*adaptiveservice.Scope)(nil)),
		"Server":              reflect.ValueOf((*adaptiveservice.Server)(nil)),
		"ServiceInfo":         reflect.ValueOf((*adaptiveservice.ServiceInfo)(nil)),
		"ServiceOption":       reflect.ValueOf((*adaptiveservice.ServiceOption)(nil)),
		"Stream":              reflect.ValueOf((*adaptiveservice.Stream)(nil)),

		// interface wrapper definitions
		"_Connection":          reflect.ValueOf((*_github_com_godevsig_adaptiveservice_Connection)(nil)),
		"_Context":             reflect.ValueOf((*_github_com_godevsig_adaptiveservice_Context)(nil)),
		"_ContextStream":       reflect.ValueOf((*_github_com_godevsig_adaptiveservice_ContextStream)(nil)),
		"_HighPriorityMessage": reflect.ValueOf((*_github_com_godevsig_adaptiveservice_HighPriorityMessage)(nil)),
		"_KnownMessage":        reflect.ValueOf((*_github_com_godevsig_adaptiveservice_KnownMessage)(nil)),
		"_Logger":              reflect.ValueOf((*_github_com_godevsig_adaptiveservice_Logger)(nil)),
		"_LowPriorityMessage":  reflect.ValueOf((*_github_com_godevsig_adaptiveservice_LowPriorityMessage)(nil)),
		"_Netconn":             reflect.ValueOf((*_github_com_godevsig_adaptiveservice_Netconn)(nil)),
		"_Stream":              reflect.ValueOf((*_github_com_godevsig_adaptiveservice_Stream)(nil)),
	}
}

// _github_com_godevsig_adaptiveservice_Connection is an interface wrapper for Connection type
type _github_com_godevsig_adaptiveservice_Connection struct {
	IValue      interface{}
	WClose      func()
	WGetNetconn func() (r0 adaptiveservice.Netconn)
	WNewStream  func() (r0 adaptiveservice.Stream)
	WRecv       func(msgPtr interface{}) (r0 error)
	WSend       func(msg interface{}) (r0 error)
	WSendRecv   func(msgSnd interface{}, msgRcvPtr interface{}) (r0 error)
}

func (W _github_com_godevsig_adaptiveservice_Connection) Close() {
	if W.WClose == nil {
		return
	}
	W.WClose()
}
func (W _github_com_godevsig_adaptiveservice_Connection) GetNetconn() (r0 adaptiveservice.Netconn) {
	if W.WGetNetconn == nil {
		return
	}
	return W.WGetNetconn()
}
func (W _github_com_godevsig_adaptiveservice_Connection) NewStream() (r0 adaptiveservice.Stream) {
	if W.WNewStream == nil {
		return
	}
	return W.WNewStream()
}
func (W _github_com_godevsig_adaptiveservice_Connection) Recv(msgPtr interface{}) (r0 error) {
	if W.WRecv == nil {
		return
	}
	return W.WRecv(msgPtr)
}
func (W _github_com_godevsig_adaptiveservice_Connection) Send(msg interface{}) (r0 error) {
	if W.WSend == nil {
		return
	}
	return W.WSend(msg)
}
func (W _github_com_godevsig_adaptiveservice_Connection) SendRecv(msgSnd interface{}, msgRcvPtr interface{}) (r0 error) {
	if W.WSendRecv == nil {
		return
	}
	return W.WSendRecv(msgSnd, msgRcvPtr)
}

// _github_com_godevsig_adaptiveservice_Context is an interface wrapper for Context type
type _github_com_godevsig_adaptiveservice_Context struct {
	IValue      interface{}
	WGetContext func() (r0 interface{})
	WGetVar     func(v interface{})
	WPutVar     func(v interface{})
	WSetContext func(v interface{})
}

func (W _github_com_godevsig_adaptiveservice_Context) GetContext() (r0 interface{}) {
	if W.WGetContext == nil {
		return
	}
	return W.WGetContext()
}
func (W _github_com_godevsig_adaptiveservice_Context) GetVar(v interface{}) {
	if W.WGetVar == nil {
		return
	}
	W.WGetVar(v)
}
func (W _github_com_godevsig_adaptiveservice_Context) PutVar(v interface{}) {
	if W.WPutVar == nil {
		return
	}
	W.WPutVar(v)
}
func (W _github_com_godevsig_adaptiveservice_Context) SetContext(v interface{}) {
	if W.WSetContext == nil {
		return
	}
	W.WSetContext(v)
}

// _github_com_godevsig_adaptiveservice_ContextStream is an interface wrapper for ContextStream type
type _github_com_godevsig_adaptiveservice_ContextStream struct {
	IValue      interface{}
	WGetContext func() (r0 interface{})
	WGetNetconn func() (r0 adaptiveservice.Netconn)
	WGetVar     func(v interface{})
	WPutVar     func(v interface{})
	WRecv       func(msgPtr interface{}) (r0 error)
	WSend       func(msg interface{}) (r0 error)
	WSendRecv   func(msgSnd interface{}, msgRcvPtr interface{}) (r0 error)
	WSetContext func(v interface{})
}

func (W _github_com_godevsig_adaptiveservice_ContextStream) GetContext() (r0 interface{}) {
	if W.WGetContext == nil {
		return
	}
	return W.WGetContext()
}
func (W _github_com_godevsig_adaptiveservice_ContextStream) GetNetconn() (r0 adaptiveservice.Netconn) {
	if W.WGetNetconn == nil {
		return
	}
	return W.WGetNetconn()
}
func (W _github_com_godevsig_adaptiveservice_ContextStream) GetVar(v interface{}) {
	if W.WGetVar == nil {
		return
	}
	W.WGetVar(v)
}
func (W _github_com_godevsig_adaptiveservice_ContextStream) PutVar(v interface{}) {
	if W.WPutVar == nil {
		return
	}
	W.WPutVar(v)
}
func (W _github_com_godevsig_adaptiveservice_ContextStream) Recv(msgPtr interface{}) (r0 error) {
	if W.WRecv == nil {
		return
	}
	return W.WRecv(msgPtr)
}
func (W _github_com_godevsig_adaptiveservice_ContextStream) Send(msg interface{}) (r0 error) {
	if W.WSend == nil {
		return
	}
	return W.WSend(msg)
}
func (W _github_com_godevsig_adaptiveservice_ContextStream) SendRecv(msgSnd interface{}, msgRcvPtr interface{}) (r0 error) {
	if W.WSendRecv == nil {
		return
	}
	return W.WSendRecv(msgSnd, msgRcvPtr)
}
func (W _github_com_godevsig_adaptiveservice_ContextStream) SetContext(v interface{}) {
	if W.WSetContext == nil {
		return
	}
	W.WSetContext(v)
}

// _github_com_godevsig_adaptiveservice_HighPriorityMessage is an interface wrapper for HighPriorityMessage type
type _github_com_godevsig_adaptiveservice_HighPriorityMessage struct {
	IValue          interface{}
	WHandle         func(stream adaptiveservice.ContextStream) (reply interface{})
	WIsHighPriority func()
}

func (W _github_com_godevsig_adaptiveservice_HighPriorityMessage) Handle(stream adaptiveservice.ContextStream) (reply interface{}) {
	if W.WHandle == nil {
		return
	}
	return W.WHandle(stream)
}
func (W _github_com_godevsig_adaptiveservice_HighPriorityMessage) IsHighPriority() {
	if W.WIsHighPriority == nil {
		return
	}
	W.WIsHighPriority()
}

// _github_com_godevsig_adaptiveservice_KnownMessage is an interface wrapper for KnownMessage type
type _github_com_godevsig_adaptiveservice_KnownMessage struct {
	IValue  interface{}
	WHandle func(stream adaptiveservice.ContextStream) (reply interface{})
}

func (W _github_com_godevsig_adaptiveservice_KnownMessage) Handle(stream adaptiveservice.ContextStream) (reply interface{}) {
	if W.WHandle == nil {
		return
	}
	return W.WHandle(stream)
}

// _github_com_godevsig_adaptiveservice_Logger is an interface wrapper for Logger type
type _github_com_godevsig_adaptiveservice_Logger struct {
	IValue  interface{}
	WDebugf func(format string, args ...interface{})
	WErrorf func(format string, args ...interface{})
	WInfof  func(format string, args ...interface{})
	WWarnf  func(format string, args ...interface{})
}

func (W _github_com_godevsig_adaptiveservice_Logger) Debugf(format string, args ...interface{}) {
	if W.WDebugf == nil {
		return
	}
	W.WDebugf(format, args...)
}
func (W _github_com_godevsig_adaptiveservice_Logger) Errorf(format string, args ...interface{}) {
	if W.WErrorf == nil {
		return
	}
	W.WErrorf(format, args...)
}
func (W _github_com_godevsig_adaptiveservice_Logger) Infof(format string, args ...interface{}) {
	if W.WInfof == nil {
		return
	}
	W.WInfof(format, args...)
}
func (W _github_com_godevsig_adaptiveservice_Logger) Warnf(format string, args ...interface{}) {
	if W.WWarnf == nil {
		return
	}
	W.WWarnf(format, args...)
}

// _github_com_godevsig_adaptiveservice_LowPriorityMessage is an interface wrapper for LowPriorityMessage type
type _github_com_godevsig_adaptiveservice_LowPriorityMessage struct {
	IValue         interface{}
	WHandle        func(stream adaptiveservice.ContextStream) (reply interface{})
	WIsLowPriority func()
}

func (W _github_com_godevsig_adaptiveservice_LowPriorityMessage) Handle(stream adaptiveservice.ContextStream) (reply interface{}) {
	if W.WHandle == nil {
		return
	}
	return W.WHandle(stream)
}
func (W _github_com_godevsig_adaptiveservice_LowPriorityMessage) IsLowPriority() {
	if W.WIsLowPriority == nil {
		return
	}
	W.WIsLowPriority()
}

// _github_com_godevsig_adaptiveservice_Netconn is an interface wrapper for Netconn type
type _github_com_godevsig_adaptiveservice_Netconn struct {
	IValue      interface{}
	WClose      func() (r0 error)
	WLocalAddr  func() (r0 net.Addr)
	WRemoteAddr func() (r0 net.Addr)
}

func (W _github_com_godevsig_adaptiveservice_Netconn) Close() (r0 error) {
	if W.WClose == nil {
		return
	}
	return W.WClose()
}
func (W _github_com_godevsig_adaptiveservice_Netconn) LocalAddr() (r0 net.Addr) {
	if W.WLocalAddr == nil {
		return
	}
	return W.WLocalAddr()
}
func (W _github_com_godevsig_adaptiveservice_Netconn) RemoteAddr() (r0 net.Addr) {
	if W.WRemoteAddr == nil {
		return
	}
	return W.WRemoteAddr()
}

// _github_com_godevsig_adaptiveservice_Stream is an interface wrapper for Stream type
type _github_com_godevsig_adaptiveservice_Stream struct {
	IValue      interface{}
	WGetNetconn func() (r0 adaptiveservice.Netconn)
	WRecv       func(msgPtr interface{}) (r0 error)
	WSend       func(msg interface{}) (r0 error)
	WSendRecv   func(msgSnd interface{}, msgRcvPtr interface{}) (r0 error)
}

func (W _github_com_godevsig_adaptiveservice_Stream) GetNetconn() (r0 adaptiveservice.Netconn) {
	if W.WGetNetconn == nil {
		return
	}
	return W.WGetNetconn()
}
func (W _github_com_godevsig_adaptiveservice_Stream) Recv(msgPtr interface{}) (r0 error) {
	if W.WRecv == nil {
		return
	}
	return W.WRecv(msgPtr)
}
func (W _github_com_godevsig_adaptiveservice_Stream) Send(msg interface{}) (r0 error) {
	if W.WSend == nil {
		return
	}
	return W.WSend(msg)
}
func (W _github_com_godevsig_adaptiveservice_Stream) SendRecv(msgSnd interface{}, msgRcvPtr interface{}) (r0 error) {
	if W.WSendRecv == nil {
		return
	}
	return W.WSendRecv(msgSnd, msgRcvPtr)
}
