// Code generated by 'yaegi extract github.com/godevsig/grepo/recorder/recorder'. DO NOT EDIT.

//go:build recordermsg
// +build recordermsg

package extension

import (
	"github.com/godevsig/grepo/recorder/recorder"
	"reflect"
)

func init() {
	Symbols["github.com/godevsig/grepo/recorder/recorder/recorder"] = map[string]reflect.Value{
		// type definitions
		"SessionRequest":  reflect.ValueOf((*recorder.SessionRequest)(nil)),
		"SessionResponse": reflect.ValueOf((*recorder.SessionResponse)(nil)),
	}
}
