// Code generated by 'yaegi extract crypto/cipher'. DO NOT EDIT.

// +build go1.16,!go1.17,stdcrypto

package stdlib

import (
	"crypto/cipher"
	"reflect"
)

func init() {
	Symbols["crypto/cipher/cipher"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewCBCDecrypter":     reflect.ValueOf(cipher.NewCBCDecrypter),
		"NewCBCEncrypter":     reflect.ValueOf(cipher.NewCBCEncrypter),
		"NewCFBDecrypter":     reflect.ValueOf(cipher.NewCFBDecrypter),
		"NewCFBEncrypter":     reflect.ValueOf(cipher.NewCFBEncrypter),
		"NewCTR":              reflect.ValueOf(cipher.NewCTR),
		"NewGCM":              reflect.ValueOf(cipher.NewGCM),
		"NewGCMWithNonceSize": reflect.ValueOf(cipher.NewGCMWithNonceSize),
		"NewGCMWithTagSize":   reflect.ValueOf(cipher.NewGCMWithTagSize),
		"NewOFB":              reflect.ValueOf(cipher.NewOFB),

		// type definitions
		"AEAD":         reflect.ValueOf((*cipher.AEAD)(nil)),
		"Block":        reflect.ValueOf((*cipher.Block)(nil)),
		"BlockMode":    reflect.ValueOf((*cipher.BlockMode)(nil)),
		"Stream":       reflect.ValueOf((*cipher.Stream)(nil)),
		"StreamReader": reflect.ValueOf((*cipher.StreamReader)(nil)),
		"StreamWriter": reflect.ValueOf((*cipher.StreamWriter)(nil)),

		// interface wrapper definitions
		"_AEAD":      reflect.ValueOf((*_crypto_cipher_AEAD)(nil)),
		"_Block":     reflect.ValueOf((*_crypto_cipher_Block)(nil)),
		"_BlockMode": reflect.ValueOf((*_crypto_cipher_BlockMode)(nil)),
		"_Stream":    reflect.ValueOf((*_crypto_cipher_Stream)(nil)),
	}
}

// _crypto_cipher_AEAD is an interface wrapper for AEAD type
type _crypto_cipher_AEAD struct {
	IValue     interface{}
	WNonceSize func() (r0 int)
	WOpen      func(dst []byte, nonce []byte, ciphertext []byte, additionalData []byte) (r0 []byte, r1 error)
	WOverhead  func() (r0 int)
	WSeal      func(dst []byte, nonce []byte, plaintext []byte, additionalData []byte) (r0 []byte)
}

func (W _crypto_cipher_AEAD) NonceSize() (r0 int) {
	if W.WNonceSize == nil {
		return
	}
	return W.WNonceSize()
}
func (W _crypto_cipher_AEAD) Open(dst []byte, nonce []byte, ciphertext []byte, additionalData []byte) (r0 []byte, r1 error) {
	if W.WOpen == nil {
		return
	}
	return W.WOpen(dst, nonce, ciphertext, additionalData)
}
func (W _crypto_cipher_AEAD) Overhead() (r0 int) {
	if W.WOverhead == nil {
		return
	}
	return W.WOverhead()
}
func (W _crypto_cipher_AEAD) Seal(dst []byte, nonce []byte, plaintext []byte, additionalData []byte) (r0 []byte) {
	if W.WSeal == nil {
		return
	}
	return W.WSeal(dst, nonce, plaintext, additionalData)
}

// _crypto_cipher_Block is an interface wrapper for Block type
type _crypto_cipher_Block struct {
	IValue     interface{}
	WBlockSize func() (r0 int)
	WDecrypt   func(dst []byte, src []byte)
	WEncrypt   func(dst []byte, src []byte)
}

func (W _crypto_cipher_Block) BlockSize() (r0 int) {
	if W.WBlockSize == nil {
		return
	}
	return W.WBlockSize()
}
func (W _crypto_cipher_Block) Decrypt(dst []byte, src []byte) {
	if W.WDecrypt == nil {
		return
	}
	W.WDecrypt(dst, src)
}
func (W _crypto_cipher_Block) Encrypt(dst []byte, src []byte) {
	if W.WEncrypt == nil {
		return
	}
	W.WEncrypt(dst, src)
}

// _crypto_cipher_BlockMode is an interface wrapper for BlockMode type
type _crypto_cipher_BlockMode struct {
	IValue       interface{}
	WBlockSize   func() (r0 int)
	WCryptBlocks func(dst []byte, src []byte)
}

func (W _crypto_cipher_BlockMode) BlockSize() (r0 int) {
	if W.WBlockSize == nil {
		return
	}
	return W.WBlockSize()
}
func (W _crypto_cipher_BlockMode) CryptBlocks(dst []byte, src []byte) {
	if W.WCryptBlocks == nil {
		return
	}
	W.WCryptBlocks(dst, src)
}

// _crypto_cipher_Stream is an interface wrapper for Stream type
type _crypto_cipher_Stream struct {
	IValue        interface{}
	WXORKeyStream func(dst []byte, src []byte)
}

func (W _crypto_cipher_Stream) XORKeyStream(dst []byte, src []byte) {
	if W.WXORKeyStream == nil {
		return
	}
	W.WXORKeyStream(dst, src)
}
