// Code generated by 'yaegi extract embed'. DO NOT EDIT.

//go:build go1.18 && !go1.19 && stdext
// +build go1.18,!go1.19,stdext

package stdlib

import (
	"embed"
	"reflect"
)

func init() {
	Symbols["embed/embed"] = map[string]reflect.Value{
		// type definitions
		"FS": reflect.ValueOf((*embed.FS)(nil)),
	}
}
