// Code generated by 'yaegi extract time/tzdata'. DO NOT EDIT.

//go:build go1.18 && !go1.19 && stdother
// +build go1.18,!go1.19,stdother

package stdlib

import (
	"reflect"
	"time/tzdata"
)

func init() {
	Symbols["time/tzdata/tzdata"] = map[string]reflect.Value{}
}
