// Code generated by 'yaegi extract time/tzdata'. DO NOT EDIT.

// +build go1.16,!go1.17,stdother

package stdlib

import (
	"reflect"
	"time/tzdata"
)

func init() {
	Symbols["time/tzdata/tzdata"] = map[string]reflect.Value{}
}
