// Code generated by 'yaegi extract unsafe'. DO NOT EDIT.

//go:build go1.18 && !go1.19 && stdunsafe
// +build go1.18,!go1.19,stdunsafe

package stdlib

import (
	"reflect"
	"unsafe"
)

func init() {
	Symbols["unsafe/unsafe"] = map[string]reflect.Value{
		// type definitions
		"Pointer": reflect.ValueOf((*unsafe.Pointer)(nil)),
	}
}
