name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+*

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        GOARCH=amd64 make full && mv -f bin/gshell bin/gshell.amd64
        GOARCH=mips64 make full && mv -f bin/gshell bin/gshell.mips64
        GOARCH=arm64 make full && mv -f bin/gshell bin/gshell.arm64
        md5sum bin/gshell* > bin/md5sum
        rm -f bin/buildtag bin/gittag

    - name: Upload files to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
