name: Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  Validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install dependencies
      run: |
        go install golang.org/x/lint/golint@latest

    - name: Build
      run: make build

    - name: Check format
      run: make format

    - name: Lint code
      run: make lint

    - name: Vet code
      run: make vet

    - name: Test
      run: make test

    - name: Coverage
      run: make coverage
